#' Line_Save Function
#'
#' This function saves parameters by lines.
#'
#' @param params List. A list containing elements generated by the \code{generate} function. This list should include the following elements:
#'   \itemize{
#'      \item Population: Numeric vector representing the initial abundances of the simulated species.
#'      \item Interactions: If \code{NULL}, a random interaction matrix is generated using \code{runif(n = n_species, min = 0, max = 1)}.
#'      \item Growths: Numeric vector representing the growth rates of the simulated species.
#'      \item Seeds: A numeric vector representing the seeds used to generate the populations, interaction matrix, and growth rates.
#'   }
#' @param uniqueID Character. A unique ID string used for saving files. This ID should be generated previously using the \code{generate_uniqueID} function.
#' @param wd Character. Path to the working directory where files will be saved. The file will be saved in the path: \code{wd/Parameters/P_uniqueID.tsv}.
#'
#' @return A list containing the generated ID and the path where the simulation file is stored.
#'
#' @examples
#'   wd <- "~/Documents/LAB_ECO"
#'
#'   # Generate parameters for simulation
#'   seeds_path <- file.path(wd, "Seeds.tsv" )
#'   params <- init_data(N_species = 2, seeds_path, C0 = 0.45, CN = 0.2, Diag_val = -0.5)
#'
#'   # Generate unique ID
#'   uniqueID <- forge_ID(wd)
#'
#'   # Save by lines
#'   line_save(params, uniqueID, wd)
#'
#' @export

line_save <- function(params, uniqueID, wd) {

  # Generate unique file paths
  pms_path <- file.path(wd, "Parameters", paste0("P_", uniqueID, ".tsv") )

  # Separate parameters
  Interactions <- params$Interactions
  Growths <- params$Growths
  Population <- params$Population
  Seeds <- params$Seeds

  # Create a function to save each section with headers
  save_section <- function(title, data, pms_path) {
    con <- file(pms_path, open = "at") # Open connection in append mode
    on.exit(close(con))
    cat("\n", title, "\n", file = pms_path, append = TRUE)
    write.table(data, file = pms_path, sep = "\t", col.names = FALSE, row.names = FALSE, append = TRUE)
    writeLines("", con) # Add a new line
  }

  # Save each section
  save_section("Interactions", Interactions, pms_path)
  save_section("Grow rates", Growths, pms_path)
  save_section("Initial populations", Population, pms_path)
  save_section("Seeds", Seeds, pms_path)

  cat("Lines saved with ID: ", uniqueID, "\n Path used:", pms_path)
}
