#' Regenerate Original Simulation Parameters from Seeds and Inputs
#'
#' This function regenerates the original simulation parameters based on the seeds and inputs used to generate them, retrieved from previously saved files.
#'
#' @param uniqueID Character. A unique ID string identifying the specific simulation. This ID should be generated previously using the \code{generate_uniqueID} function.
#' @param wd Character. The working directory where the `Seed_save.tsv` file, generated by \link{params_seed_saver}, is located.
#'
#' @details
#' This function regenerates the original simulation parameters using the seed and input data from the `Seed_save.tsv` file. It returns the parameters in the form of a list containing the interaction matrix, growth rates, and initial population abundances.
#' 
#' @return A list containing the following elements:
#' \itemize{
#'   \item \code{Interactions}: A matrix representing interaction coefficients between species. It is regenerated by setting a previously used seed and following this procedure: 
#'     A binomial distribution with a success probability of `CN` is used to determine whether the interaction will be negative. 
#'     The resulting number is then multiplied by another binomial distribution with a success probability of `C0` to determine if the interaction will be null (0). 
#'     Finally, this product is multiplied by a uniform distribution between 0 and 1 to obtain the final interaction value. 
#'     The diagonal of the interaction matrix is filled with the value of `Diag_val` (user input).
#'     
#'   \item \code{Growths}: A numeric vector of the growth rates for the simulated species. It is regenerated by setting a seed and using 
#'     a uniform distribution between 0.001 and 1, representing the growth rate of each species.
#'         
#'   \item \code{Population}: A numeric vector of the initial abundances of the species. It is regenerated by setting a seed and using 
#'     a uniform distribution between 0.01 and 1, representing the initial populations of each species.
#' }
#' 
#' @examples
#' wd <- "~/Documents/LAB_ECO/Simulations"
#' 
#' # Generate parameters
#' seeds_path <- file.path(wd, "Seeds.tsv")
#' params <- forge_data(N_species = 10, seeds_path, C0 = 0.45, CN = 0.2, Diag_val = -0.5)
#' 
#' # Generate unique ID
#' uniqueID <- forge_id(wd)
#' 
#' # Save parameters by seeds
#' params_seed_saver(N_species = 10,  C0 = 0.45, CN = 0.2, Diag_val = -0.5, params, uniqueID, wd)
#' 
#' # Read parameters by seed
#' params_seed_reader(uniqueID, wd)
#' 
#' @export


params_seed_reader <- function(uniqueID, wd) {
  
  # attach package 
  requireNamespace("utils")
  
  Ps_path <- file.path(wd, "Parameters", "Seeds_save.tsv")
  Ps_table <- utils::read.delim(Ps_path, sep = "\t", header = TRUE)
  
  result <- subset(Ps_table, ID_simulation == uniqueID)
  
  N_species <- result$N_specs
  C0 <- result$Prob_0
  CN <- result$Prob_neg
  Diag_val <- result$Diagonal
  
  # Generate Initial Population vector
  set.seed(result$Population_seed)
  Pobl <- stats::runif(N_species, min = 0.1, max = 1)
  
  # Generate Interaction matrix
  set.seed(result$Interactions_seed)
  P_neg <- stats::rbinom(N_species * N_species, 1, CN)
  tmp <- stats::rbinom(N_species * N_species, 1, 1 - C0) * ifelse(P_neg != 0, stats::runif(N_species * N_species, min = 0, max = 1), 
                                                                  -stats::runif(N_species * N_species, min = 0, max = 1))
  inter <- matrix(tmp, nrow = N_species, ncol = N_species)
  diag(inter) <- Diag_val
  
  # Generate Growth rates
  set.seed(result$Growth_seed)
  Grow <- stats::runif(N_species, min = 0.001, max = 1)
  
  # Return parameters as a list
  params <- list(Population = Pobl,
                 Interactions = inter,
                 Growths = Grow)
  
  return(params)
} 
