#' Regenerate Original Simulation Parameters from Seeds and Inputs
#'
#' This function regenerates the original simulation parameters based on the seeds and inputs used to generate them, retrieved from previously saved files.
#'
#' @param uniqueID Character. A unique ID string identifying the specific simulation. This ID should be generated previously using the \code{generate_uniqueID} function.
#' @param wd Character. The working directory where the `Seed_save.tsv` file, generated by \link{params_seed_saver}, is located.
#'
#' @details
#' This function regenerates the original simulation parameters, using the seed and input data from the `Seed_save.tsv` file. It returns the parameters in the form of a list containing the interaction matrix, growth rates, and initial population abundances.
#' 
#' @return A list containing the following elements:
#'   \itemize{
#'     \item \code{Interactions}: A matrix representing interaction coefficients between species.
#'     \item \code{Growths}: A numeric vector of the growth rates for the simulated species.
#'     \item \code{Population}: A numeric vector of the initial abundances of the species.
#'   }
#' 
#' @examples
#' # Example usage
#' wd <- "~/Documents/LAB_ECO/Simulations"
#' x <- params_seed_reader(uniqueID = "e9591f", wd)
#' 
#' 
#' # Code to verify if the params_seed_readr returns the same data
#' # isTRUE( all.equal(x$Interactions, params$Interactions) )
#' @export

params_seed_reader <- function(uniqueID, wd) {
  
  # attach package 
  requireNamespace("utils")
  
  Ps_path <- file.path(wd, "Parameters", "Seeds_save.tsv")
  Ps_table <- utils::read.delim(Ps_path, sep = "\t", header = TRUE)
  
  result <- subset(Ps_table, ID_simulation == uniqueID)
  
  N_species <- result$N_specs
  C0 <- result$Prob_0
  CN <- result$Prob_neg
  Diag_val <- result$Diagonal
  
  # Generate Initial Population vector
  set.seed(result$Population_seed)
  Pobl <- stats::runif(N_species, min = 0.1, max = 1)
  
  # Generate Initial Population vector
  set.seed(result$Population_seed)
  Pobl <- stats::runif(N_species, min = 0.1, max = 1)
  
  # Generate Initial Population vector
  set.seed(result$Interactions_seed)
  P_neg <- stats::rbinom(N_species * N_species, 1, CN)
  tmp <- stats::rbinom(N_species * N_species, 1, 1 - C0) * ifelse(P_neg != 0, stats::runif(N_species * N_species, min = 0, max = 1), 
                                                                  -stats::runif(N_species * N_species, min = 0, max = 1))
  inter <- matrix(tmp, nrow = N_species, ncol = N_species)
  diag(inter) <- Diag_val
  
  # Generate Growth rates
  set.seed(result$Growth_seed)
  Grow <- stats::runif(N_species, min = 0.001, max = 1)
  
  # Return parameters as a list
  params <- list(Population = Pobl,
                 Interactions = inter,
                 Growths = Grow)
  
  return(params)
} 
