#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' 
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero. 
#' 
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives
regenerate <- function(index) {
  
  n_species <- as.numeric(index[["n_species"]])
  
  #------------------Populations-----------------------------#
  set.seed(as.numeric(index[["Pop_seed"]]))
  x0 <- stats::runif(n_species, min = 0.1, max = 1)
  
  #------------------------Growth Rates---------------------#
  set.seed(as.numeric(index[["Growth_seed"]]))
  mu <- stats::runif(n_species, min = 0.001, max = 1)
  
  #--------------------Interactions-------------------------#
  
  #' Create a matrix full of ones and diagonal of 0
  M <- 1 - diag(n_species)
  
  #' Define proportions for zero and negative values
  p_noint <- as.numeric(index[["p_noint"]])
  p_neg <- as.numeric(index[["p_neg"]])
  A_seed <- as.numeric(index[["A_seed"]])
  
  #' Set seed for reproducibility
  set.seed(A_seed)
  
  #' Testin purpose line
  Noff_diag <- sum(M == 1) 
  num_0 <- floor(p_noint * Noff_diag)
  num_negs <- floor(p_neg * (Noff_diag - num_0))
  num_pos <- Noff_diag - (num_0 + num_negs)
  
  #' Fill zeroes
  indices_1 <- which(M == 1, arr.ind = TRUE)
  sampled_0 <- sample(x = indices_1, size = num_0)
  zero_elements <- indices_1[sampled_0, ]
  M[zero_elements] <- 0
  
  #' Assign -0.5 to the diagonal
  diag(M) <- -0.5
  
  #' Assign negative interactions
  indices_1 <- which(M == 1, arr.ind = TRUE)
  sampled_neg <- sample(x = indices_1, size = num_negs)
  neg_elements <- indices_1[sampled_neg, ]
  M[neg_elements] <- -runif(num_negs, min = 0, max = 1)
  
  #' Assign positive interactions
  indices_1 <- which(M == 1, arr.ind = TRUE)
  sampled_pos <- sample(x = indices_1, size = num_pos)
  pos_elements <- indices_1[sampled_pos, ]
  M[pos_elements] <- runif(num_negs, min = 0, max = 1)
  
  # Extract ID
  id <- index[["id"]]
  
  # Return parameters as a list
  params <- list(x0 = x0,
                 M = M,
                 mu = mu,
                 id = id,
                 n = n_species)
  
  return(params)
}
