---
title: "Exp05-report"
author: "Manuel Rivera"
date: "2025-03-25"
output: 
  html_document:
    toc: true           # Enable Table of Contents
    theme: sandstone
    toc_float: true
    collapsed: false
    smooth_scroll: true
---

## Load parameters 

### Attach Packages
```{r eval=TRUE, warning=FALSE}
library(dplyr) 
library(tidyr)
library(tidyverse)
library(svglite)

```

## Load parameters table

```{r eval=TRUE}
# For cluster environment, use the appropriate path: 
path <- "/mnt/atgc-d3/sur/users/mrivera/glv-research/Data/Exp05-D25M03.tsv"
params_table <- data.table::fread(path)
head(params_table)
```


### Verify parameters

```{r eval=TRUE}
# Source function to regenerate parameters
source("/mnt/atgc-d3/sur/users/mrivera/glv-research/GIT-gLV/D20M03-tmpdir/gLV-Params.R")
print(regenerate)
```

```{r eval=TRUE}

# Load Na counting table
na_table <- data.table::fread("/mnt/atgc-d3/sur/users/mrivera/glv-research/Results/Exp05-D25M03/Na-count-02.tsv")

# Rename columns 
result <- na_table %>%
  set_names(c("id", "count"))  %>%
   mutate(across(count, ~ ifelse(. > 0, 1, 0))) %>%
  full_join(params_table, by = join_by(id)) %>%
  select(count, n_species, p_neg, p_noint) %>%
  group_by(n_species, p_noint) %>%
 summarize(sims_done = n(), succes = n() - sum(count), fails = sum(count), .groups = "drop")  # Count total simulations 

head(result)
```


## Create graphs


```{r  eval=TRUE}
#' Blackbox theme
#' 
#' ggplot2 theme that places a black margin on every
#' panel
#'
#' @param border.size Thickness of the margin.
#'
#' @return A \code{theme gg} object.
#' @export
#' @author Sur Herrera Paredes
theme_blackbox <- function(border.size = 3){
  theme(axis.text = element_text(color="black"),
        axis.title = element_text(face="bold"),
        panel.background = element_rect(color = "black",
                                        linewidth = border.size,
                                        fill = NA),
        panel.grid = element_blank())
}
```

Failed simulations plot:
```{r eval=TRUE}
library(ggplot2)

p1 <- result %>%
  ggplot(aes(x = p_noint, y = succes)) +
  geom_point(alpha = 0.7) +  # Create the ridge lines
  labs(title = "Exo05 p_noint vs Success", x = "p_noint", y = "Success") +
  facet_wrap(~n_species) +
  theme_blackbox()

p1
ggsave("/mnt/atgc-d3/sur/users/mrivera/glv-research/GIT-gLV/Notebooks/Exp05-success.svg", width = 6, height = 4)
```

Failed extinctions plots... (missing)
```{r eval=TRUE}

#========= Get extinctions that were not performed ============
# Get simulations where extinctions were calculated
path <- "/mnt/atgc-d3/sur/users/mrivera/glv-research/GIT-gLV/D20M03-tmpdir/test-02.error"
err_file <- readLines(path)

# Get ids
tmp <- err_file[grep("^Simulation\\s.*\\sfailed", err_file, ignore.case = TRUE)]
ids <- sub("^Simulation\\s([a-zA-Z0-9]+)\\sfailed\\s.*", "\\1", tmp)

# Get simulations where extinctions where performed
library(dplyr)
path <- "/mnt/atgc-d3/sur/users/mrivera/glv-research/Data/Exp05-D25M03.tsv"
params_table <- data.table::fread(path)
cat("The number of simulations where at leat 25% of species survived was:",
    nrow(params_table)-length(ids))

# Parameters of simulations with extinction
ext_params <- params_table %>%
  filter(!(id %in% ids))


#========= Read extinctions ============
library(dplyr)
path <- file.path(wd, "Results", "Exp05-D25M03", "Extinctions-02")
rds_files <- file.path(path, paste0("Ext_", ext_params$id,".rds"))
x <- rds_files[1]



data <- readRDS(x) %>%
  select(-data) %>%
  group_by(ID)
```

