#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero.
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#' (`Pr(M_ij < 0 | M_ij != 0)`)
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives. 

ctrl_regenerate <- function(index) {
  
  #------------------Species number--------------------------#
  n_species <- as.numeric(index[["n_species"]])
  
  #------------------Populations-----------------------------#
  set.seed(as.numeric(index[["x0_seed"]]))
  x0 <- stats::runif(n_species, min = 0.1, max = 1)
  
  #------------------Growth Rates----------------------------#
  set.seed(as.numeric(index[["mu_seed"]]))
  mu <- stats::runif(n_species, min = 0.001, max = 1)
  
  #------------------Keystone specie-------------------------#
  keystone <- as.numeric(index[["keys"]])

  #--------------------Interactions-------------------------#
  # Define proportions for zero 
  p_noint <- as.numeric(index[["p_noint"]])

  # Create matrix with NA values and fill the diagonal with -0.5
  M <- matrix(NA, nrow = n_species, ncol = n_species)

  # Define the number of interactions
  total <- n_species * (n_species - 1)     # Total off-diagonal elements
  num_noint <- floor(p_noint * total)      # null-interactions

  # Negative-non-zero interactions
  num_negs <- total - num_noint       

  # Create the interaction vector
  set.seed(as.numeric(index[["A_seed"]]))
  interaction_values <- c(rep(0, num_noint),-runif(num_negs, min = 0, max = 1))
  
  # Shuffle the interaction vector
  interaction_values <- sample(interaction_values)
  
  # Assign to off-diagonal elements
  M[upper.tri(M, diag = FALSE) | lower.tri(M, diag = FALSE)] <- interaction_values
  
  # Add keystone interactions  
  M[keystone,] = runif(n_species, min = 0.8, max = 1)
  diag(M) <- -0.5

  # Optional: Round if needed
  M <- round(M, digits = 5)

  # Extract ID
  id <- index[["id"]]
  
  # Return parameters as a list
  params <- list(x0 = x0,
                 M = M,
                 mu = mu,
                 id = id,
                 n = n_species,
                 key = keystone)
  
  return(params)
}
