#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero.
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#' (`Pr(M_ij < 0 | M_ij != 0)`)
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives. 

ctrl_regenerate <- function(index) {
  
  #------------------Species number--------------------------#
  n_species <- as.numeric(index[["n_species"]])
  
  #------------------Populations-----------------------------#
  set.seed(as.numeric(index[["x0_seed"]]))
  x0 <- stats::runif(n_species, min = 0.1, max = 1)
  
  #------------------Growth Rates----------------------------#
  set.seed(as.numeric(index[["mu_seed"]]))
  mu <- stats::runif(n_species, min = 0.001, max = 1)
  
  #------------------Keystone specie-------------------------#
  k <- as.numeric(index[["keys"]])

  #--------------------Interactions-------------------------#
  # Create matrix of TRUE for off-diagonal positions
  mask <- matrix(TRUE, n_species, n_species)
  diag(mask) <- FALSE                             # remove diagonal
  mask[k, ] <- FALSE                              # remove row k
  M <- matrix(0, n_species, n_species)            # matrix to fill

  # Total number of off-diagonal elements excluding row k
  # (n**2 - n) is the number of off-diagonal elements
  # (n-1) removes the elements in row k
  # (n**2 - n) - (n-1) = n**2 - 2*n + 1
  total = (n_species**2) - (2 * n_species) + 1 

  # Define the number of interactions
  p_noint <- as.numeric(index[["p_noint"]])
  num_noint <- floor(p_noint * total)     # null-interactions
  num_negs <- total - num_noint           # negative-interactions  

  # Interaction values
  set.seed(as.numeric(index[["A_seed"]]))
  values <- c(rep(0, num_noint),-runif(num_negs, min = 0, max = 1))
  values <- sample(values)  # Shuffle 

  # Assign values
  M[mask] <- values                              # off-diagonal and no keystone interactions 
  M[k,] = runif(n_species, min = 0.8, max = 1)   # Add keystone interactions 
  diag(M) <- -0.5                                # Diagonal
  M <- round(M, digits = 4)

  # Return parameters as a list  
  return(list(x0 = x0, M = M, mu = mu, id = index[["id"]], n = n_species, keystone = k))
}
