#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero.
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#' (`Pr(M_ij < 0 | M_ij != 0)`)
#' @param k keystone specie in the community
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives. 

build_params_ctrls <- function(index) {
  
  n_species <- as.numeric(index[["n_species"]])
  
  #------------------Populations-----------------------------#
  set.seed(as.numeric(index[["x0_seed"]]))
  x0 <- stats::runif(n_species, min = 0.1, max = 1)
  
  #------------------------Growth Rates---------------------#
  set.seed(as.numeric(index[["mu_seed"]]))
  mu <- stats::runif(n_species, min = 0.001, max = 1)
  
  #--------------------Interactions-------------------------#
    
  #' Define proportions for zero and negative values
  p_noint <- as.numeric(index[["p_noint"]])
  p_neg <- as.numeric(index[["p_neg"]])
  k = as.numeric(index[["key"]])  # Keystone specie

  # Define the number of interactions
  # Removed diagonal elements n
  # Removed one species interaction from the pool (n_species - 1)
  total = (n_species**2) - n_species - (n_species - 1)
  num_noint = floor(p_noint * total)      # null-interactions
  remaining = total - num_noint           # Non-zero-interactions
  num_negs = floor(p_neg * remaining)     # Negative interactions
  num_pos = remaining - num_negs
  
  # Create the interaction vector
  set.seed(as.numeric(index[["A_seed"]]))
  interaction_values <- c(rep(0, num_noint),-runif(num_negs, min = 1, max = 2),runif(num_pos, min = 0, max = 1))
  
  # Shuffle the interaction vector
  set.seed(as.numeric(index[["A_seed"]]))
  interaction_values <- sample(interaction_values)

  # Create matrix of TRUE masking
  mask <- matrix(TRUE, n_species, n_species)    # mask matrix
  diag(mask) <- FALSE                           # remove diagonal
  mask[,k] <- FALSE                            # remove keystone COLUMN
  
  # Generate matrix to fill
  M <- matrix(NA, n_species, n_species)         # values matrix
  M[mask] <- interaction_values  # off-diagonal and off keystone row values
  set.seed(as.numeric(index[["A_seed"]]))
  M[,k] <- -runif(n_species, min = 0, max = 1)                  # keystone column values  
  diag(M) <- -0.5                # diagonal values

  # Optional: Round if needed
  M <- round(M, digits = 5)
  
  # Extract ID
  id <- index[["id"]]
  
  # Return parameters as a list
  params <- list(x0 = x0, M = M, mu = mu, id = id, n = n_species)
  
  return(params)
}
