#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero.
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#' (`Pr(M_ij < 0 | M_ij != 0)`)
#' @param k keystone specie in the community
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives. 

gen_Kboost_params <- function(row) {
    # Load parameters
    n  <- as.numeric(row[["n_species"]])
    k  <- as.numeric(row[["key"]])
    p_noint <- as.numeric(row[["p_noint"]])
    p_neg   <- as.numeric(row[["p_neg"]])
    # Abort if k does not exist
    if (!("key" %in% names(row))) {
      print('Aborting, k does not exist') 
      return(NULL)
    }
    # Initial population
    set.seed(as.numeric(row[["x0_seed"]]))
    x0 <- runif(n, min = 0.1, max = 1)
    # Growth rates
    set.seed(as.numeric(row[["mu_seed"]]))
    mu <- runif(n, min = 0.001, max = 1)
    # Interaction counts
    n_offdiag <- n^2 - n                                # off-diagonal elements 
    n_noint   <- floor(p_noint * n_offdiag)             # null interactions
    n_neg     <- floor(p_neg * (n_offdiag - n_noint))   # negative interactions
    n_pos     <- n_offdiag - n_noint - n_neg            # positive interactions
    # Interaction matrix
    set.seed(as.numeric(row[["A_seed"]]))
    M        <- matrix(NA, n, n)
    diag(M)  <- -0.5
    M[!diag(n)] <- sample( c(rep(0, n_noint),-runif(n_neg, min = 0, max = 1), runif(n_pos, min = 0, max = 1)) ) 
    M[, k] <- M[, k] * 10
    M  <- round(M, 5)
    list(x0 = x0, M = M, mu = mu, id = row[["id"]], n = n)
}
