#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero.
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#' (`Pr(M_ij < 0 | M_ij != 0)`)
#' @param k keystone specie in the community
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives. 
#' @examples
#' index = list(n_species = 5, p_noint = 0.5, p_neg = 1, key = 1, id = "example_id", x0_seed = 123, mu_seed = 456, A_seed = 789)
#' gen_cascade_params(index)

gen_cascade_params <- function(index) {
  #-------------------Parameters-------------------------#
  n_species <- as.numeric(index[["n_species"]])
  id <- index[["id"]]
  #------------------Populations-----------------------------#
  set.seed(as.numeric(index[["x0_seed"]]))
  x0 <- stats::runif(n_species, min = 0.1, max = 1)
  #------------------------Growth Rates---------------------#
  set.seed(as.numeric(index[["mu_seed"]]))
  mu <- stats::runif(n_species, min = 0.001, max = 1)
  #--------------------Interactions-------------------------#
  # Section: Define proportions for zero and negative values
  p_noint <- as.numeric(index[["p_noint"]])
  p_neg <- as.numeric(index[["p_neg"]])
  k = as.numeric(index[["key"]])  # Keystone specie
  #------------------------
  # Define the number of interactions
  # Removed diagonal elements n
  total = (n_species**2) - n_species 
  num_noint = floor(p_noint * total)      # null-interactions
  remaining = total - num_noint           # Non-zero-interactions
  num_negs = floor(p_neg * remaining)     # Negative interactions
  num_pos = remaining - num_negs
  #------------------------
  # Create the interaction vector
  a_seed = as.numeric(index[["A_seed"]])
  set.seed(a_seed)
  interaction_values <- c(rep(0, num_noint),-runif(num_negs, min = 0, max = 1),runif(num_pos, min = 0, max = 1))
  # Shuffle the interaction vector
  set.seed(a_seed)
  interaction_values <- sample(interaction_values)
  #------------------------
  # Create matrix of TRUE masking
  mask <- matrix(TRUE, n_species, n_species)    # mask matrix
  diag(mask) <- FALSE                           # remove diagonal
  # Generate matrix to fill
  M <- matrix(NA, n_species, n_species)     # values matrix
  M[mask] <- interaction_values             # add values
  diag(M) <- -0.5                           # fill diagonal
  #------------------------
  # Section: Generate cascading effects
  # Create matrix of TRUE masking
  mask <- matrix(TRUE, n_species, n_species)    # mask matrix
  diag(mask) <- FALSE                           # remove diagonal
  # Cascade is the vector containing the sequence.
  whom_rows = seq_along(1:n_species)[-k]
  set.seed(a_seed)
  whom_rows = sample(whom_rows)  # shuffle the order of the affected species
  who_cols = c(k, whom_rows)       # who
  for (i in seq_along(whom_rows)) {
    # print(paste0(">> Applying cascade effect: ", who_cols[i], " affects ", whom_rows[i]))
    M[whom_rows[i], who_cols[i]] = M[whom_rows[i], who_cols[i]] * 10
  }
  # Optional: Round if needed
  M <- round(M, digits = 5)
  # Return parameters as a list
  params <- list(x0 = x0, M = M, mu = mu, id = id, n = n_species)
  return(params)
}
