#' The next function is for generating the parameters from a TSV file with the parameters and
#' id that will be used, this TSV file had to be previously generated by the `Grid method`.
#' 
#' @param n_species Number of species to simulate
#' @param p_noint Probability of no interaction, i.e. probability that a
#' non-diagonal element in the interaction matrix is zero.
#' @param p_neg Probability of a negative effect, i.e. probability that
#' a non-diagonal non-zero element of the interaction matrix is negative
#' (`Pr(M_ij < 0 | M_ij != 0)`)
#'
#' Each parameter is calculated in the next way:
#' `x0` This parameter represents the initial population of each species at time 0. It is
#' calculated from a uniform distribution (from 0 to 1).
#' 
#' `mu` This parameters represents the growth rates of each species across all generations. 
#' It is calculated from a uniform distribution (from 0.001 to 1)
#' 
#' `M` Interaction matrix with diagonal `-0.5` and non diagonal elements with zeroes,
#'  positive interactions or negatives. 

regenerate <- function(index) {
  
  n_species <- as.numeric(index[["n_species"]])
  
  #------------------Populations-----------------------------#
  set.seed(as.numeric(index[["Pop_seed"]]))
  x0 <- stats::runif(n_species, min = 0.1, max = 1)
  
  #------------------------Growth Rates---------------------#
  set.seed(as.numeric(index[["Growth_seed"]]))
  mu <- stats::runif(n_species, min = 0.001, max = 1)
  
  #--------------------Interactions-------------------------#
  
  # Create matrix with NA values and fill the diagonal with -0.5
  M <- matrix(NA, nrow = n_species, ncol = n_species)
  diag(M) <- -0.5
  
  #' Define proportions for zero and negative values
  p_noint <- as.numeric(index[["p_noint"]])
  p_neg <- as.numeric(index[["p_neg"]])
  p_pos <- as.numeric(index[["p_pos"]])
  
  # Define the number of interactions
  num_off_diag <- n_species * (n_species - 1)  # Total off-diagonal elements
  num_noint <- floor(p_noint * num_off_diag)   # Number of null interactions
  num_negs <- floor(p_neg * (num_off_diag - num_noint)) # Number of negative interactions
  num_pos <- num_off_diag - (num_noint + num_negs) # Remaining are positive interactions
  
  # Create the interaction vector
  set.seed(as.numeric(index[["A_seed"]]))
  interaction_values <- c(rep(0, num_noint),
                          -runif(num_negs, min = 0, max = 1),
                          runif(num_pos, min = 0, max = 1))
  
  # Shuffle the interaction vector
  interaction_values <- sample(interaction_values)
  
  # Assign to off-diagonal elements
  M[upper.tri(M, diag = FALSE) | lower.tri(M, diag = FALSE)] <- interaction_values
  
  # Optional: Round if needed
  M <- round(M, digits = 5)
  
  # Extract ID
  id <- index[["id"]]
  
  # Return parameters as a list
  params <- list(x0 = x0,
                 M = M,
                 mu = mu,
                 id = id,
                 n = n_species)
  
  return(params)
}