#' Seed_saver Function
#'
#' This function saves the specified parameters in a table format. The parameters include the number of species, interaction probabilities, diagonal values of the interaction matrix, and seed values used in different aspects of the simulation.
#'
#' @param N_specs Integer. Number of species involved in the simulation.
#' @param C0 Numeric. Probability of no interaction between species (i.e., 0 interaction).
#' @param CN Numeric. Probability of negative interaction (<0) between species.
#' @param V_diag Numeric vector. Diagonal values used in the interaction matrix.
#' @param params List. Parameters used in the simulation, specifically \code{params$Semilla} containing:
#' \itemize{
#'   \item \code{Semilla[1]}: Seed used for initial populations.
#'   \item \code{Semilla[2]}: Seed used for the interaction matrix.
#'   \item \code{Semilla[3]}: Seed used for species growth rates.
#' }
#' @param uniqueID Character. A unique ID string used for saving files. This ID should be generated previously using the \code{generate_uniqueID} function.
#' @param wd Character. Path to the working directory where files will be saved. The file will be saved in the path: \code{wd/Parameters/Seeds_save.tsv}.
#'
#' @details
#' The function stores the provided parameters in a table format for future reference. The table includes species count, interaction probabilities,
#' matrix diagonal values, and seed values.
#'
#' @examples
#' # Example usage
#'
#' wd <- "~/Documents/LAB_ECO"
#'
#' # Initial parameters
#' N_species = 2
#' C0 = 0.45
#' CN = 0.2
#' Diag_val = -0.5
#'
#' # Generate parameters
#' seeds_path <- file.path(wd, "Seeds.tsv" )
#' params <- generate (N_species, seeds_path, C0, CN, Diag_val)
#'
#' # Generate unique ID
#' uniqueID <- generate_uniqueID(wd)
#'
#' # Seed_saver function
#' Seed_saver(N_species, C0, CN, Diag_val, params, uniqueID, wd)
#'
#' @export

Seed_saver <- function(N_species, C0, CN, Diag_val, params, uniqueID, wd) {

  # Save seeds information
  seeds_df <- data.frame(
    'ID_simulation' = uniqueID,
    "N_specs" = N_species,
    "Prob_0" = C0,
    "Prob_neg" = CN,
    "Diagonal" = Diag_val,
    "Population_seed" = params$Seeds[1],
    "Interacs_seed" = params$Seeds[2],
    "Growth_seed" = params$Seeds[3]
  )

  Ps_path <- file.path(wd, "Parameters", "Seeds_save.tsv")

  if (file.exists(Ps_path)) {
    existing_data <- read.delim(Ps_path, sep = "\t", header = TRUE)
    combined_data <- rbind(existing_data, seeds_df)
  } else {
    combined_data <- seeds_df
  }

  # Save table
  write.table(combined_data, file = Ps_path, sep = "\t", row.names = FALSE, col.names = TRUE)

  cat("Seeds saved with ID: ", uniqueID, "\n Path:", Ps_path)
}

#' Line_Save Function
#'
#' This function saves parameters by lines.
#'
#' @param wd Character. Path to the working directory where files will be saved. The file will be saved in the path: \code{wd/Parameters/P_uniqueID.tsv}.
#' @param uniqueID Character. A unique ID string used for saving files. This ID should be generated previously using the \code{generate_uniqueID} function.
#' @param params List. A list containing elements generated by the \code{generate} function. This list should include the following elements:
#'   \itemize{
#'     \item Interactions: If \code{NULL}, a random interaction matrix is generated using \code{runif(n = n_species, min = 0, max = 1)}.
#'     \item Growths: Numeric vector representing the growth rates of the simulated species.
#'     \item Population: Numeric vector representing the initial abundances of the simulated species.
#'     \item Seeds: Numeric vector representing the seeds used to generate the interaction matrix, growth rates, and populations.
#'   }
#'
#' @return A list containing the generated ID and the path where the simulation file is stored.
#'
#' @examples
#' # Example usage
#'
#' wd <- "~/Documents/LAB_ECO"
#'
#' # Initial parameters
#' N_species <- 2
#' C0 <- 0.45
#' CN <- 0.2
#' Diag_val <- -0.5
#'
#' # Generate parameters
#' seeds_path <- file.path(wd, "Seeds.tsv")
#' params <- generate(N_species, seeds_path, C0, CN, Diag_val)
#'
#' # Generate unique ID
#' uniqueID <- generate_uniqueID(wd)
#'
#' # Save by lines
#' Line_Save(N_species, C0, CN, Diag_val, output_matrix, params)
#'
#' @export

Line_Saver <- function(params, uniqueID, wd) {

  # Generate unique file paths
  pms_path <- file.path(wd, "Parameters", paste0("P_", uniqueID, ".tsv") )

  # Separate parameters
  Interactions <- params$Interactions
  Growths <- params$Growths
  Population <- params$Population
  Seeds <- params$Seeds

  # Assign names and prepare data for saving
  name <- paste("S_", 1:nrow(Interactions))
  rownames(Interactions) <- name
  colnames(Interactions) <- name
  names(Growths) <- name
  names(Population) <- name
  names(Seeds) <- c("Seed_population", "Seed_interactions", "Seed_growths")

  # Create a function to save each section with headers
  save_section <- function(title, data, pms_path) {
    con <- file(pms_path, open = "at") # Open connection in append mode
    cat("\n", title, "\n", file = pms_path, append = TRUE)
    write.table(data, file = pms_path, sep = "\t", col.names = NA, append = TRUE)
    writeLines("", con) # Add a new line
  }

  # Save each section
  save_section("Interactions", Interactions, pms_path)
  save_section("Grow rates", Growths, pms_path)
  save_section("Initial populations", Population, pms_path)
  save_section("Seeds", Seeds, pms_path)

  cat("Lines saved with ID: ", uniqueID, "\n Path used:", pms_path)
}
